# Generated by Django 2.0 on 2018-01-19 18:49

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(posts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
